# Build IRS 990 E-Filers Database


Information about this data can be found at:  https://aws.amazon.com/public-data-sets/irs-990/

**Accessing IRS 990 Filings on AWS**

Each electronic 990 filing is available as a unique XML file in the "irs-form-990" S3 bucket in the US East (N. Virginia) region. Schemas for electronic 990 filings are available on the IRS website. Each filing is named based on the year it was filed and a unique identifier. For example, we can tell that the filing named "201541349349307794_public.xml" was filed in 2015 because the file name starts with "2015." "41349349307794" is the unique identifier of the filing.

An index listing all of the available filings is available at s3://irs-form-990/index.json. This file includes basic information about each filing including the name of the filer, the Employer Identificiation Number (EIN) of the filer, the date of the filing, and the path to download the filing.

All of the data is publicly accessible via the S3 bucket's HTTPS endpoint at https://s3.amazonaws.com/irs-form-990. No authentication is required to download data over HTTPS. For example, the index file can be accessed at https://s3.amazonaws.com/irs-form-990/index.json and the example filing mentioned above can be accessed at https://s3.amazonaws.com/irs-form-990/201541349349307794_public.xml.




## BUILD THE INDEX DATABASE OF ALL ELECTRONIC FILERS


```R


# INSTALL REQUIRED PACKAGES

install.packages( "jsonlite" )
install.packages( "R.utils" )


# LOAD REQUIRED PACKAGES

library( jsonlite )
library( R.utils )


### CREATE A DIRECTORY FOR YOUR DATA

getwd()

dir.create( "IRS Nonprofit Data" )

setwd( "./IRS Nonprofit Data" )


### DOWNLOAD FILES AND UNZIP

electronic.filers <- "https://s3.amazonaws.com/irs-form-990/index.json.gz"

download.file( url=electronic.filers, "electronic.json.gz" )

gunzip("electronic.json.gz", remove=TRUE )  


# CREATE A DATA FRAME OF ELECTRONIC FILERS FROM IRS JSON FILES

data.ef <- fromJSON( txt="electronic.json" )[[1]]

nrow( data.ef )




# REFORMAT DATE FROM YYYY-MM TO YYYY

data.ef$FilingYear <- substr( data.ef$TaxPeriod, 1, 4 )




# DROP UNRELIABLE YEARS

table( data.ef$FilingYear ) # note that some records are nonsensical

data.ef <- data.ef[ data.ef$FilingYear > 2009 & data.ef$FilingYear < 2016 , ]

table( data.ef$FilingYear, useNA="ifany" )

nrow( data.ef )




# EXCLUDE DATA THAT IS NOT AVAILABLE IN ELECTRONIC FORMAT

table( data.ef$IsElectronic, data.ef$IsAvailable )

data.ef <- data.ef[ data.ef$IsAvailable == TRUE , ]

nrow( data.ef )


```





## DESCRIPTIVES


```R

length( unique( data.ef$EIN ) )  # number of unique orgs

table( table( data.ef$EIN, useNA="ifany" ) )  # available panel spells



# why do we have some organizations with more spells than years ?

table.ein <- table( data.ef$EIN, useNA="ifany" )

table.ein[ table.ein > 6 , ]

data.ef[ data.ef$EIN == "830229733" , ]  # submitted two filings in 2013 


```







## WRITE DATA TO YOUR FAVORITE FORMAT


```R

# AS R DATA SET

saveRDS( data.ef, file="ElectronicFilers.csv" )


# AS CSV

write.csv( data.ef, file="ElectronicFilers.csv", row.names=F )


# IN STATA

library( foreign )
write.dta( data.ef, file="ElectronicFilers.dta" )


# IN SPSS

library( foreign )
write.foreign( data.ef, file="ElectronicFilers.sav", package="SPSS" )

```

