# 990-N Postcard Filers

Info including data dictionary can be found at: https://apps.irs.gov/app/eos/forwardToEpostDownload.do


Internal Revenue Service United States Department of the Treasury
Form 990-N (e-Postcard) Data Download Layout

The Form 990-N (e-Postcard) filing information will be listed in rows, with each field of data separated by a pipe ('|') symbol. The following table describes the format and order of each field in a row, representing one Form 990-N (e-Postcard) filing.


## DATA DICTIONARY


Field				| Notes
----------------------------------------|----------------------------------------------------------
EIN				| Required
Tax Year				| Required
Organization Name			| Required
Gross Receipts Under $25,000		| Required, 'T' represents True and 'F' represents False.
Terminated				| Required, 'T' represents True and 'F' represents False.
Tax Period Begin Date			| Required, Format: MM-DD-YYYY
Tax Period End Date			| Required, Format: MM-DD-YYYY
Website URL				| Optional
Officer Name			| Required
Officer Address Line 1			| Required
Officer Address Line 2			| Optional
Officer Address City			| Required if country is US. Optional if country is not US
Officer Address Province		| Optional if country is not US. Null if country is US
Officer Address State			| Required if country is US. Null if country is not US
Officer Address Postal Code		| Required if country is US. Optional if country is not US
Officer Address Country			| Required
Organization Address Line 1		| Required
Organization Address Line 2		| Optional
Organization Address City		| Required if country is US. Optional if country is not US
Organization Address Province		| Optional if country is not US. Null if country is US
Organization Address State		| Required if country is US. Null if country is not US
Organization Address Postal Code	            | Required if country is US. Optional if country is not US
Organization Address Country		| Required
Doing Business As Name 1		| Optional
Doing Business As Name 2		| Optional
Doing Business As Name 3		| Optional




## BUILD THE DATASET


```R 


# create subdirectory for the data

dir.create( "IRS Nonprofit Data" )

setwd( "./IRS Nonprofit Data" )



# download and unzip

file.url <- "https://apps.irs.gov/pub/epostcard/data-download-epostcard.zip"

download.file( url=file.url, "epostcard.zip" )

unzip( "epostcard.zip" )

file.remove( "epostcard.zip" )

dat.990n <- read.delim( file="data-download-epostcard.txt", 
            header = FALSE, 
            sep = "|", 
            quote = "",
            dec = ".", 
            fill = TRUE,  
            colClasses="character"
          )


# add header information - variable names

var.names <- c("EIN", "Tax.Year", "Organization.Name", "Gross.Receipts.Under.$25,000", 
"Terminated", "Tax.Period.Begin.Date", "Tax.Period.End.Date", 
"Website.URL", "Officer.Name", "Officer.Address.Line.1", "Officer.Address.Line.2", 
"Officer.Address.City", "Officer.Address.Province", "Officer.Address.State", 
"Officer.Address.Postal.Code", "Officer.Address.Country", "Organization.Address.Line.1", 
"Organization.Address.Line.2", "Organization.Address.City", "Organization.Address.Province", 
"Organization.Address.State", "Organization.Address.Postal.Code", 
"Organization.Address.Country", "Doing.Business.As.Name.1", "Doing.Business.As.Name.2", 
"Doing.Business.As.Name.3")

names( dat.990n ) <- var.names

rm( var.names )


# change Tax.Year from YYYY-MM to YYYY

dat.990n$FileYear < substr( dat.990n$Tax.Year, 1, 4 )

```


## EXPORT THE DATASET

```R

# AS R DATA SET

saveRDS( dat.990n, file="PostcardFilers.rds" )


# AS CSV

write.csv( dat.990n, "PostcardFilers.csv", row.names=F )


# IN STATA

library( foreign )
write.dta( dat.990n, "PostcardFilers.dta" )


# IN SPSS  - creates a text file and a script for reading it into SPSS

library( foreign )
write.foreign( df=dat.990n, datafile="PostcardFilers.txt", codefile="CodeToLoadDataInSPSS.txt", package="SPSS" )

# if package 'foreign' is not installed first try:  install.packages("foreign")

```
